# Generated by Django 3.0.5 on 2020-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coronaData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('active', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
        ),
    ]
